import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Muhammad Reza Nur Rifqi',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const anim_gradient = {
    background: "linear-gradient(90deg, hsla(277, 79%, 84%, 1) 0%, hsla(204, 95%, 77%, 1) 100%)",
    backgroundSize : "400% 400%",
    animation : "gradient 25s ease infinite",
  };
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;600&display=swap" rel="stylesheet" />
        <link rel="icon" href="favicon.ico" type="image/png" sizes="32x32" />
      </head>
      <body className={inter.className} className="bg-[url('/background.jpg')] bg-cover">{children}</body>
    </html>
  )
}
